// Generated by CoffeeScript 1.4.0
(function() {
  var Ace;

  Ace = angular.module('Ace', []);

  /* --------------------------------------------
       Begin ace-directives.coffee
  --------------------------------------------
  */


  /* --------------------------------------------
       Begin ace-controller.coffee
  --------------------------------------------
  */


  Ace.controller('AceEditCtrl', ['$scope', function($scope) {}]);

}).call(this);
