// Generated by CoffeeScript 1.3.3
var MDProcessor, aMarked;

if (!(window.console && console.log)) {
  (function() {
    var console, len, methods, noop, _results;
    noop = function() {};
    methods = ['assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error', 'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log', 'markTimeline', 'profile', 'profileEnd', 'markTimeline', 'table', 'time', 'timeEnd', 'timeStamp', 'trace', 'warn'];
    len = methods.length;
    console = window.console = {};
    _results = [];
    while (len--) {
      _results.push(console[methods[len]] = noop);
    }
    return _results;
  })();
}

/* --------------------------------------------
     Begin app.coffee
--------------------------------------------
*/


MDProcessor = (function() {

  function MDProcessor(scope, elem, attrs) {
    this.scope = scope;
    this.elem = elem;
    this.attrs = attrs;
  }

  MDProcessor.prototype.regexp = {
    h1: /^(?:#{1}\s?)([^#]+)/gi
  };

  MDProcessor.prototype.process = function(md) {
    _.each(this.regexp, function(exp) {
      var match;
      match = exp.test(md);
      if (match) {
        return console.log(md.match(exp));
      }
    });
    return this.scope.preview = md;
  };

  return MDProcessor;

})();

aMarked = angular.module('aMarked', []);

/* --------------------------------------------
     Begin directives.coffee
--------------------------------------------
*/


aMarked.directive('markdownProcessor', function() {
  return {
    restrict: 'A',
    link: function(scope, elem, attrs) {
      var p;
      p = new MDProcessor(scope, elem, attrs);
      return scope.$watch('markdown', function(md) {
        return p.process(md);
      });
    }
  };
});

/* --------------------------------------------
     Begin filters.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin services.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin controllers.coffee
--------------------------------------------
*/


aMarked.controller('MainAppCtrl', [
  '$scope', function($scope) {
    $scope.title = "ng-Bootstrap";
    $scope.filename = "Untitled";
    $scope.markdown = '';
    return $scope.preview = '';
  }
]);
