// Generated by CoffeeScript 1.3.3
var MDProcessor, Stor, aMarked;

if (!(window.console && console.log)) {
  (function() {
    var console, len, methods, noop, _results;
    noop = function() {};
    methods = ['assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error', 'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log', 'markTimeline', 'profile', 'profileEnd', 'markTimeline', 'table', 'time', 'timeEnd', 'timeStamp', 'trace', 'warn'];
    len = methods.length;
    console = window.console = {};
    _results = [];
    while (len--) {
      _results.push(console[methods[len]] = noop);
    }
    return _results;
  })();
}

/* --------------------------------------------
     Begin app.coffee
--------------------------------------------
*/


MDProcessor = (function() {

  function MDProcessor(scope, elem, attrs) {
    this.scope = scope;
    this.elem = elem;
    this.attrs = attrs;
  }

  MDProcessor.prototype.matchers = [
    {
      tag: "p",
      exp: /^([^#\*]+)/i
    }, {
      tag: "h1",
      exp: /^(?:#{1}\s?)([^#]+)/i
    }, {
      tag: "h2",
      exp: /^(?:#{2}\s?)([^#]+)/i
    }, {
      tag: "h3",
      exp: /^(?:#{3}\s?)([^#]+)/i
    }, {
      tag: "h4",
      exp: /^(?:#{4}\s?)([^#]+)/i
    }, {
      tag: "h5",
      exp: /^(?:#{5}\s?)([^#]+)/i
    }, {
      tag: "h6",
      exp: /^(?:#{6}\s?)([^#]+)/i
    }, {
      tag: "li",
      exp: /^(?:\*{1}\s?)([^*\r\n]+)/i
    }
  ];

  MDProcessor.prototype.process = function(md) {
    var lines, output, self;
    self = this;
    lines = md.split(/\n/gi);
    output = [];
    _.each(lines, function(line) {
      var markupMatches;
      if (line != null) {
        markupMatches = _.filter(self.matchers, function(matcher) {
          return matcher.exp.test(line) === true;
        });
        if ((markupMatches != null) && markupMatches.length) {
          return _.each(markupMatches, function(matcher) {
            var el, exp, tag;
            tag = matcher.tag;
            exp = matcher.exp;
            el = self.buildElement(tag, exp, line);
            return output.push(el);
          });
        }
      }
    });
    window.op = output;
    self.needsParent(output);
    this.scope.preview = output;
    return console.log(lines);
  };

  MDProcessor.prototype.buildElement = function(tag, exp, line) {
    var content, d, el, txt;
    d = document;
    content = line.match(exp)[1];
    txt = d.createTextNode(content);
    el = d.createElement(tag);
    el.appendChild(txt);
    return el;
  };

  MDProcessor.prototype.needsParent = function(output) {
    var $els, el, els, i, len, next, prev, tag, _results;
    $els = $(output);
    els = this.jqToArray($els);
    len = els.length;
    i = 0;
    _results = [];
    while (i < len) {
      el = els[i];
      tag = el.tagName;
      prev = i === 0 ? '' : els[i - 1].tagName;
      next = i + 1 === len ? '' : els[i + 1].tagName;
      if (tag === 'LI') {
        if (prev !== 'LI') {

        }
      }
      _results.push(i++);
    }
    return _results;
  };

  MDProcessor.prototype.jqToArray = function($els) {
    var el, els, _i, _len;
    els = [];
    for (_i = 0, _len = $els.length; _i < _len; _i++) {
      el = $els[_i];
      els.push(el);
    }
    return els;
  };

  return MDProcessor;

})();

Stor = (function() {

  function Stor() {
    this.amp = amplify.store;
  }

  Stor.prototype.get = function(key) {
    return this.amp(key);
  };

  Stor.prototype.set = function(key, val, exp) {
    if (exp == null) {
      exp = null;
    }
    return this.amp(key, val, exp);
  };

  Stor.prototype.del = function(key) {
    return this.amp(key, null);
  };

  return Stor;

})();

aMarked = angular.module('aMarked', []);

/* --------------------------------------------
     Begin directives.coffee
--------------------------------------------
*/


aMarked.directive('markdownProcessor', function() {
  return {
    restrict: 'A',
    link: function(scope, elem, attrs) {
      var p;
      p = new MDProcessor(scope, elem, attrs);
      return scope.$watch('markdown', function(md) {
        scope.$emit('markdownChange', md);
        return p.process(md);
      });
    }
  };
});

aMarked.directive('markdownPreview', function() {
  return {
    restrict: 'A',
    link: function(scope, elem, attrs) {
      return scope.$watch('preview', function(els) {
        return $(elem).empty().append(els);
      });
    }
  };
});

/* --------------------------------------------
     Begin filters.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin services.coffee
--------------------------------------------
*/


/* --------------------------------------------
     Begin controllers.coffee
--------------------------------------------
*/


aMarked.controller('MainAppCtrl', [
  '$scope', function($scope) {
    var getSavedState, stor;
    $scope.stor = stor = new Stor();
    $scope.title = "ng-Bootstrap";
    $scope.filename = "Untitled";
    $scope.preview = '';
    getSavedState = (function() {
      var filename, md;
      md = stor.get('aMarked');
      filename = stor.get('');
      return $scope.markdown = md != null ? md : '';
    })();
    return $scope.$on('markdownChange', function(e, md) {
      return stor.set('aMarked', md);
    });
  }
]);
